site_name: Studio Caju API Documentation
site_description: API documentation for Studio Caju backend
site_author: Studio Caju Team

repo_url: https://github.com/contreras3991/studio-caju
edit_uri: edit/main/backend/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference:
    - Overview: api_index.md
    - Authentication: api_login.md
    - Users: api_users.md
    - Clients: api_clients.md
    - Projects: api_projects.md
    - Tasks: api_tasks.md
    - Tenants: api_tenants.md
    - Superuser: api_superuser.md
  - Validation:
    - Client Identifier: client_identifier_validation.md
  - Changes:
    - CPF/CNPJ Validation (2023-07-14): changes/2023-07-14-cpf-cnpj-validation.md
    - CPF/CNPJ Validation (2025-04-20): changes/cpf-cnpj-validation-20250420.md
    - Task Feature (2025-04-20): changes/task-feature-20250420.md
  - Developer Guide: dev-docs.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/contreras3991/studio-caju 