name: backend continuous integration
on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copiar os arquivos do diretório
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalando as dependências do projeto
        run: poetry install --no-root

      - name: Executar testes
        run: poetry run task test